<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Captured screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=errorAt15_39.jpeg ><img src=errorAt15_39.jpeg height=1280 width =720></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-13T10:09:18Z" name="Page object test cases" finished-at="2022-07-13T10:09:38Z" duration-ms="19820">
    <groups>
    </groups>
    <test started-at="2022-07-13T10:09:18Z" name="Login Test" finished-at="2022-07-13T10:09:21Z" duration-ms="2349">
      <class name="com.apoorv.testcases.LoginTest">
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.apoorv.testcases.LoginTest@76fe6cdc]" started-at="2022-07-13T10:09:19Z" name="loginTest" data-provider="dp" finished-at="2022-07-13T10:09:20Z" duration-ms="1502" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=JUSTdance@96, username=apoorvlifeok@outlook.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test fail
at org.testng.Assert.fail(Assert.java:96)
at com.apoorv.testcases.LoginTest.loginTest(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Captured screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=errorAt15_39.jpeg ><img src=errorAt15_39.jpeg height=1280 width =720></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.apoorv.testcases.LoginTest -->
    </test> <!-- Login Test -->
    <test started-at="2022-07-13T10:09:21Z" name="Create account Test" finished-at="2022-07-13T10:09:38Z" duration-ms="16971">
      <class name="com.apoorv.testcases.CreateAccountTest">
        <test-method signature="createAccountTest(java.util.Hashtable)[pri:0, instance:com.apoorv.testcases.CreateAccountTest@3b4a1a75]" started-at="2022-07-13T10:09:21Z" name="createAccountTest" data-provider="dp" finished-at="2022-07-13T10:09:38Z" duration-ms="16966" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{accountName=Rahul, =}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
      </class> <!-- com.apoorv.testcases.CreateAccountTest -->
      <class name="com.apoorv.testcases.LoginTest">
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.apoorv.testcases.LoginTest@76fe6cdc]" started-at="2022-07-13T10:09:38Z" name="TearDown" finished-at="2022-07-13T10:09:39Z" duration-ms="391" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.apoorv.testcases.LoginTest -->
    </test> <!-- Create account Test -->
  </suite> <!-- Page object test cases -->
</testng-results>
